spring:
  application:
    name: book-service
  datasource:
    url: jdbc:h2:file:~/IdeaProjects/h2/data/demo
    username: sa
    password: pwd
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 7001

management:
  endpoints:
    web:
      exposure:
        include: mappings


